Repository pathoplexus/pathoplexus, pull requests merged in 2024-11, with the labels that each got.

#271 Update Loculus version to 284915
  pathoplexus_app/values.yaml
Labels: preview

#270 Correct curator sop
  monorepo/website/src/images/CurationReviseButton.png
  monorepo/website/src/images/CurationRevisionForm.png
  monorepo/website/src/images/CurationVersionComment.png
  monorepo/website/src/pages/docs/how-to/curator-sop.mdx
Labels: preview, review please

#273 Update Revise-submissions.mdx
  monorepo/website/src/pages/docs/how-to/revise-submissions.mdx
Labels: preview

#274 Disable link checker for CI for now, still allow manual triggering
  .github/workflows/broken-link-check.yml
Labels: preview

#262 News items for 1 Nov
  .github/workflows/broken-link-check.yml
  monorepo/website/public/gifs/news/2024-11-01-autumn-update/checkbox.gif
  monorepo/website/src/pages/news/2024-11-01-autumn-update.mdx
  monorepo/website/src/pages/news/index.astro
Labels: preview

#294 fix: use github pages to host sequences not raw.githubusercontent to avoid 403 errors/rate limits
  loculus_values/values.yaml
Labels: preview

#298 Update FAQ to include swissunis grant
  monorepo/website/src/pages/about/faq.mdx
Labels: documentation, preview

#299 Update Loculus version to 281b6e
  loculus_values/environment_specific_values/demo.yaml
  loculus_values/environment_specific_values/main.yaml
  loculus_values/environment_specific_values/production.yaml
  loculus_values/environment_specific_values/staging.yaml
  loculus_values/values.yaml
  pathoplexus_app/values.yaml
Labels: preview, breaking

#306 Update Statutes & Add new Minutes
  monorepo/website/public/about/governance/minutes/2024-11-25_PathoplexusGAmeeting.pdf
  monorepo/website/src/pages/about/governance/minutes.mdx
  monorepo/website/src/pages/about/governance/pathoplexus-statutes.mdx
Labels: preview
