Repository pathoplexus/pathoplexus, pull requests merged in 2024-10, with the labels that each got.

#207 Remove staging from muffet link check
  .github/workflows/broken-link-check.yml
Labels: preview

#217 Add Today's GA minutes to website
  monorepo/website/public/about/governance/minutes/2024-10-04_PathoplexusGAmeeting.pdf
  monorepo/website/src/pages/about/governance/minutes.mdx
Labels: preview

#216 Add new Pathoplexus members to website
  monorepo/website/src/images/peterVanHeusden-square.jpg
  monorepo/website/src/pages/about/governance/eb-guidelines.mdx
  monorepo/website/src/pages/about/members.mdx
Labels: preview

#222 ENA deposition config updates, required by loculus changes
  loculus_values/environment_specific_values/production.yaml
  loculus_values/environment_specific_values/staging.yaml
  loculus_values/values.yaml
Labels: preview

#226 feat(ci): highlight breaking changes in Loculus bump PRs, allow non-main Loculus target commit, use PAT to trigger website action from auto-PRs
  .github/workflows/bump-main-loculus-version-to-latest.yaml
Labels: enhancement, ci

#232 Update Loculus version to c723c5
  loculus_values/values.yaml
  pathoplexus_app/values.yaml
Labels: preview

#238 Replace lapis-pathoplexus with lapis.pathoplexus in query API examples
  monorepo/website/src/pages/docs/how-to/search-download-seqs-api.mdx
Labels: bug, documentation, preview

#241 docs: document group edit feature
  monorepo/website/src/components/InfoBox.astro
  monorepo/website/src/components/asides/CautionBox.astro
  monorepo/website/src/components/asides/InfoBox.astro
  monorepo/website/src/pages/about/terms-of-use/open-data.mdx
  monorepo/website/src/pages/about/terms-of-use/restricted-data.mdx
  monorepo/website/src/pages/docs/how-to/add-orcid-account.mdx
  monorepo/website/src/pages/docs/how-to/add-remove-user-group.mdx
  monorepo/website/src/pages/docs/how-to/approve-submissions.mdx
  monorepo/website/src/pages/docs/how-to/authentication-api.mdx
  monorepo/website/src/pages/docs/how-to/create-account.mdx
  monorepo/website/src/pages/docs/how-to/create-group.mdx
  monorepo/website/src/pages/docs/how-to/curator-sop.mdx
  monorepo/website/src/pages/docs/how-to/edit-account.mdx
  monorepo/website/src/pages/docs/how-to/edit-group.mdx
  monorepo/website/src/pages/docs/how-to/edit-submissions.mdx
  monorepo/website/src/pages/docs/how-to/generate-seqset.mdx
  monorepo/website/src/pages/docs/how-to/remove-orcid-account.mdx
  monorepo/website/src/pages/docs/how-to/report-sequence-issues.mdx
  monorepo/website/src/pages/docs/how-to/revise-submissions.mdx
  monorepo/website/src/pages/docs/how-to/revoke-sequences.mdx
  monorepo/website/src/pages/docs/how-to/search-download-seqs-api.mdx
  monorepo/website/src/pages/docs/how-to/search-sequences-website.mdx
  monorepo/website/src/pages/docs/how-to/upload-sequences.mdx
  monorepo/website/src/pages/docs/how-to/view-submitted-sequences.mdx
Labels: preview

#247 Update Loculus version to 712fde
  pathoplexus_app/values.yaml
Labels: preview

#180 Adding Meera to SAB page
  monorepo/website/src/images/silhouette-square.jpg
  monorepo/website/src/pages/about/sab.mdx
Labels: preview

#254 Update Loculus version to 385013
  pathoplexus_app/values.yaml
Labels: preview

#255 Update Loculus version to 335f12
  pathoplexus_app/values.yaml
Labels: preview

#257 Update Loculus version to 78fec9
  pathoplexus_app/values.yaml
Labels: preview

#260 Temporarily use 3 prepro replicas to speed up deployment of changes
  loculus_values/values.yaml
Labels: preview

#263 Update Loculus version to 0e4a6f
  pathoplexus_app/values.yaml
Labels: preview

#267 Add Felix to Pathoplexus dev team
  monorepo/website/src/images/felixHennig-square.jpg
  monorepo/website/src/pages/about/development-team.mdx
Labels: preview

#266 Add Resolutions & Minutes from EB in Sept-Oct 2024
  monorepo/website/public/about/governance/minutes/2024-10-22_PathoplexusEBmeeting_summary.pdf
  monorepo/website/public/about/governance/minutes/2024-10-30_EB_Resolutions.pdf
  monorepo/website/src/pages/about/governance/minutes.mdx
Labels: preview
