Repository pathoplexus/pathoplexus, pull requests merged in 2024-09, with the labels that each got.

#84 feat: Add robots noindex headers to all but production
  loculus_values/environment_specific_values/production.yaml
  loculus_values/values.yaml
  pathoplexus_app/values.yaml
Labels: preview

#94 ci: use short loculus sha in branch name, bump actions
  .github/workflows/bump-main-loculus-version-to-latest.yaml
  .github/workflows/self-approval-check.yml
Labels: preview

#108 Improvements to `sync.sh` script used for website dev
  .github/workflows/website.yml
  README.md
  sync.sh
Labels: review please

#123 chore: include file-downloads & outlinks in plausible config
  loculus_values/values.yaml
Labels: preview

#126 Add EB Resolutions from 12 Sept #125
  monorepo/website/public/about/governance/minutes/2024-09-12_EB_Resolutions.pdf
  monorepo/website/src/pages/about/governance/minutes.mdx
Labels: preview

#128 News Item 13 Sept
  monorepo/website/src/pages/news/2024-09-13-two-weeks.mdx
  monorepo/website/src/pages/news/index.astro
Labels: preview

#134 feat: add broken-link-checker gh action and fix broken links
  .github/workflows/broken-link-check.yml
  monorepo/website/src/pages/about/governance/data-submission.mdx
  monorepo/website/src/pages/about/governance/minutes.mdx
  monorepo/website/src/pages/about/terms-of-use/data-use-terms.mdx
  monorepo/website/src/pages/about/terms-of-use/privacy-policy.mdx
  monorepo/website/src/pages/about/terms-of-use/terms-of-service.mdx
  monorepo/website/src/pages/news/index.astro
Labels: preview

#50 feat(website): EB page tweaks
  monorepo/website/src/components/Team.astro
  monorepo/website/src/pages/about/eb.mdx
Labels: preview

#150 fix: allow HTML tags in news excerpts
  monorepo/website/src/pages/news/index.astro
Labels: preview

#153 Add a link to Loculus near the top of Pathoplexus README
  README.md
Labels: discussion

#154 fix: don't ingest continent as geoLocAdmin2
  loculus_values/values.yaml
Labels: preview

#159 chore: use prod secrets for staging to allow cloning of keycloak from prod to staging
  loculus_values/environment_specific_values/demo.yaml
  loculus_values/environment_specific_values/production.yaml
  loculus_values/environment_specific_values/staging.yaml
Labels: review please

#163 docs: add how-to guide for API submission
  monorepo/website/src/components/InfoBox.astro
  monorepo/website/src/pages/about/terms-of-use/open-data.mdx
  monorepo/website/src/pages/about/terms-of-use/restricted-data.mdx
  monorepo/website/src/pages/docs/how-to/approve-submissions.mdx
  monorepo/website/src/pages/docs/how-to/authentication-api.mdx
  monorepo/website/src/pages/docs/how-to/edit-account.mdx
  monorepo/website/src/pages/docs/how-to/upload-sequences.mdx
Labels: preview

#194 switch on debug logging in ingest
  loculus_values/values.yaml
Labels: preview

#187 Increase timeout length for muffet
  .github/workflows/broken-link-check.yml
Labels: preview
